[tool.poetry]
name = "videocompressor"
version = "0.1.0"
description = ""
authors = ["recursion-team"]
packages = [
    { include = "client" },
    { include = "server" }
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
